"""changes reflections table

Revision ID: 20d9367d3681
Revises: 70e78a1a447a
Create Date: 2024-06-29 18:28:57.070219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d9367d3681'
down_revision = '70e78a1a447a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refelctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('reflection')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refelctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflection', sa.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
