"""corrected table reflections spelling

Revision ID: 5d41eef3dfb6
Revises: 20d9367d3681
Create Date: 2024-06-29 19:13:19.467601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d41eef3dfb6'
down_revision = '20d9367d3681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_reflections_strategy_id_strategies')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_reflections_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('refelctions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refelctions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name='fk_refelctions_strategy_id_strategies'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_refelctions_teacher_id_teachers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reflections')
    # ### end Alembic commands ###
